### ISSUE TITLE
Can't retrieve the contact information

### ISSUE THREAD

**Issue by aldovilardy** [Rainbow-CPaaS/Rainbow-Node-SDK#1]
Hi  @oanguenot  @diegofn
Whe I try to get the contact information using the method **contacts.getContactByJid(message.fromJid)** always return a null value, maybe that method doesn't work or need to define the class _Contact_.

`rainbowSDK.events.on('rainbow_onmessagereceived', function(message) {`
`    // Retrieve the contact information when receiving a message from him`
`    var contact = rainbowSDK.contacts.getContactByJid(message.fromJid);`
`    rainbowSDK.im.sendMessageToJid("Hello " + contact.fistname, message.fromJid);`
`});`

**Comment by oanguenot** [comment]
Hi @aldovilardy 

Your issue should be solved with the version 0.10.13

The getContactByJid was looking only in the local list of contacts. Now if not found, a search is made on server side to find the contact information. 

Depending on the privacy rules between users, the information retrieved can be less consistent (less information) than when the contact belongs to your list of contacts. In that case, all information are accessible.
